"""
combined_fig1_schematic.py
===========================
Figure 1 — Schematic / Cartoon (docs/paper1_expansion_plan.md, P.P. June 9 spec).

  Panel A: BLG and CASEIN structures side by side, key structural feature
           highlighted (calyx / N-terminal hydrophobic patch) in the amber
           accent shared by both COLORS["calyx"] and COLORS["patch"] in
           plot_style.py — same color role, same meaning, both species.
  Panel B: simulation box schematic, VACUUM | MOLECULE | WATER | VACUUM
           along Z, drawn to the actual locked box geometry (not illustrative
           guesses — read from the real .gro files, see dimensions below).

Inputs (already rendered, not regenerated by this script):
  results/figures/render/blg_calyx_crop.png   — VMD NewCartoon, calyx=amber
  results/figures/render/cas_patch_crop.png   — VMD NewCartoon, N-term=amber
  (see scripts/figures/vmd/render_blg.tcl / render_cas.tcl for the VMD
  source — re-run through VMD headless from that directory:
    vmd -dispdev text -e render_blg.tcl
    vmd -dispdev text -e render_cas.tcl
  each writes a Targa file mislabeled .png (VMD/Tachyon quirk — "render
  TachyonInternal" ignores the .png extension); convert + crop with:
    sips -s format png {blg_calyx,cas_patch}_raw.png --out X.png
  then crop to content bounds before compositing — see git history for
  the exact PIL crop snippet used the first time.
  if the renders ever need regenerating.)

Box geometry (read directly from confout.gro box-vector lines, 2026-08-08):
  BLG bulk (pre-stretch, outputs_BLG/CENTER/NVT_100ps/nvt.gro): 12.00 x 12.00 x  7.00 nm
  BLG slab  (production,  outputs_BLG/CENTER/MD1000/confout.gro): 12.00 x 12.00 x 35.00 nm
  CAS bulk (pre-stretch, outputs_CAS/CENTER/NPT_v2/confout.gro): 16.06 x 14.05 x  8.66 nm
  CAS slab (production,  outputs_CAS/CENTER/NVT_SLAB_v2/casein_slab_v2.gro): 16.00 x 14.00 x 35.00 nm
Both species share the same Z=35 nm slab convention. Vacuum is added
symmetrically by editconf -c, so vacuum-per-side = (35 - bulk_Lz) / 2.

NOTE — open items not resolved here, per docs/paper1_expansion_plan.md:
  - Panel B drawn as separate boxes per species (P.P.'s doc flags "one per
    box, or combined? [CONFIRM WITH P.P.]" as unresolved) — this is the
    documented-open default, not a decision made on her behalf.
  - Which Z-end the protein starts at (vs. diffusing to an interface over
    the run) is drawn schematically at the upper interface for both, purely
    for layout — not a claim about actual starting coordinates.

Usage:
  /Users/mac2022-1/opt/anaconda3/envs/research-env/bin/python3 \
      scripts/figures/combined_fig1_schematic.py
"""

from pathlib import Path
import sys

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib import gridspec
from matplotlib.patches import Rectangle, FancyBboxPatch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
from plot_style import apply_style, COLORS, double_width, savefig_pdf  # noqa: E402
from utils import INK, MUTED  # noqa: E402

apply_style()

RENDER_DIR = ROOT / "results" / "figures" / "render"
OUT_DIR = ROOT / "results" / "figures" / "paper"
OUT_DIR.mkdir(parents=True, exist_ok=True)

AMBER = COLORS["calyx"]  # == COLORS["patch"], same amber, deliberately

# ── locked box geometry (nm), read from the real .gro files — see docstring ──
BOXES = {
    "BLG": dict(
        display="β-Lactoglobulin", lx=12.00, ly=12.00,
        lz_slab=35.00, lz_bulk=7.00,
        struct_img=RENDER_DIR / "blg_calyx_crop.png",
        feature_label="Calyx",
    ),
    "CAS": dict(
        display="β-Casein", lx=16.00, ly=14.00,
        lz_slab=35.00, lz_bulk=8.66,
        struct_img=RENDER_DIR / "cas_patch_crop.png",
        feature_label="N-term patch (1–25)",
    ),
}


def panel_a(fig, gs_row, species):
    cfg = BOXES[species]
    ax = fig.add_subplot(gs_row)
    img = mpimg.imread(cfg["struct_img"])
    ax.imshow(img)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.set_title(cfg["display"], fontsize=9, fontweight="bold", color=INK, pad=4)
    ax.text(0.5, -0.06, cfg["feature_label"], transform=ax.transAxes,
             ha="center", va="top", fontsize=7.5, color=AMBER, fontweight="bold")
    return ax


def panel_b(fig, gs_row, species):
    cfg = BOXES[species]
    ax = fig.add_subplot(gs_row)

    lz = cfg["lz_slab"]
    lz_bulk = cfg["lz_bulk"]
    vac = (lz - lz_bulk) / 2.0
    # band boundaries, z increasing upward: [0, vac] vacuum, [vac, vac+mol]
    # molecule at the upper water/vacuum interface, rest of the bulk band water
    mol_band = min(1.2, lz_bulk * 0.18)  # thin band representing the protein
    z0_vac_bot = 0.0
    z1_water_bot = vac
    z2_mol = vac + (lz_bulk - mol_band)   # molecule sits at the TOP of the water band
    z3_water_top = vac + lz_bulk
    z4_vac_top = lz

    box_w = 0.62  # drawing width (arbitrary units, box is drawn schematically)
    x0 = 0.5 - box_w / 2

    def band(y0, y1, color, alpha=1.0):
        ax.add_patch(Rectangle((x0, y0), box_w, y1 - y0,
                                facecolor=color, edgecolor="none", alpha=alpha, zorder=1))

    VACUUM_C = "#F2F2F2"
    WATER_C = "#CFE3F2"
    band(z0_vac_bot, z1_water_bot, VACUUM_C)
    band(z1_water_bot, z2_mol, WATER_C)
    band(z2_mol, z3_water_top, AMBER, alpha=0.85)   # molecule band
    band(z3_water_top, z4_vac_top, VACUUM_C)

    # outer box border + periodic-boundary hint (dashed top/bottom = same face)
    ax.add_patch(Rectangle((x0, 0), box_w, lz, facecolor="none",
                            edgecolor=INK, linewidth=0.9, zorder=3))
    for yb in (0, lz):
        ax.plot([x0, x0 + box_w], [yb, yb], ls=(0, (2, 2)), lw=0.7, color=MUTED, zorder=3)

    # band labels, right of the box
    labels = [
        ((z0_vac_bot + z1_water_bot) / 2, "VACUUM"),
        ((z1_water_bot + z2_mol) / 2, "WATER"),
        ((z2_mol + z3_water_top) / 2, "MOLECULE"),
        ((z3_water_top + z4_vac_top) / 2, "VACUUM"),
    ]
    for y, text in labels:
        ax.text(x0 + box_w + 0.03, y, text, fontsize=6.3, va="center", ha="left",
                 color=INK, fontweight="bold" if text == "MOLECULE" else "normal")

    # dimension annotations
    ax.annotate("", xy=(x0 - 0.05, 0), xytext=(x0 - 0.05, lz),
                arrowprops=dict(arrowstyle="<->", lw=0.7, color=MUTED))
    ax.text(x0 - 0.09, lz / 2, f"{lz:.0f} nm", rotation=90, fontsize=6.3,
            ha="center", va="center", color=MUTED)
    ax.text(0.5, -0.05, f"{cfg['lx']:.0f} × {cfg['ly']:.0f} nm footprint",
            transform=ax.transAxes, ha="center", va="top", fontsize=6.3, color=MUTED)

    ax.set_xlim(0, 1)
    ax.set_ylim(-2, lz + 2)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.set_title(f"{cfg['display']} slab", fontsize=8, color=INK, pad=4)
    return ax


def main():
    fig = plt.figure(figsize=(double_width, 6.4))
    gs = gridspec.GridSpec(2, 2, figure=fig, height_ratios=[1.0, 1.35],
                            hspace=0.38, wspace=0.15,
                            left=0.10, right=0.90, top=0.94, bottom=0.06)

    panel_a(fig, gs[0, 0], "BLG")
    panel_a(fig, gs[0, 1], "CAS")
    panel_b(fig, gs[1, 0], "BLG")
    panel_b(fig, gs[1, 1], "CAS")

    fig.text(0.02, 0.97, "A", fontsize=12, fontweight="bold", color=INK)
    fig.text(0.02, 0.60, "B", fontsize=12, fontweight="bold", color=INK)

    out = OUT_DIR / "PAPER_FIG1_SCHEMATIC.png"
    savefig_pdf(fig, out)


if __name__ == "__main__":
    main()
