"""
make_fig3_preview.py — Fig 3 layout preview from gate/RMSF cache
=================================================================
Generates Fig 3 with identical layout to the fixed make_fig3_activation.py
but sources data entirely from pre-computed caches + synthetic noise for
panels (b) Rg and (d) patch RMSD (key numbers from paper key values).

Use this to validate label / legend layout WITHOUT running full trajectory
analysis. The real figure must still be generated by make_fig3_activation.py
once trajectory compute has run.

Output: results/figures/PAPER_FIG3_PREVIEW.png
"""
import sys
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from numpy.lib.stride_tricks import sliding_window_view

ROOT     = Path(__file__).resolve().parent.parent.parent
GATE_DIR = ROOT / "results" / "gate_analysis"
OUT      = ROOT / "results" / "figures" / "paper" / "PAPER_FIG3_PREVIEW.png"

# ── Load cached data ──────────────────────────────────────────────────────────
z     = np.load(GATE_DIR / "R1_gate.npz")
t_r   = z["time"]          # ns, 2001 frames (0.5 ns stride)
sasa_r = z["sasa"]         # nm² — same hydrophobic SASA as panel (a)

resids_c = np.load(GATE_DIR / "rmsf_center.resids.npy")
rmsf_c   = np.load(GATE_DIR / "rmsf_center.rmsf.npy")
resids_r = np.load(GATE_DIR / "rmsf_r1.resids.npy")
rmsf_r   = np.load(GATE_DIR / "rmsf_r1.rmsf.npy")

# ── Synthetic panels from paper key numbers ───────────────────────────────────
rng = np.random.default_rng(42)
rg_r    = rng.normal(1.496, 0.009, len(t_r))       # Rg: 1.496 ± 0.009 nm
t_p     = np.linspace(0, t_r[-1], len(t_r) // 5)   # coarser stride for patch RMSD
rmsd_p  = 0.24 + rng.normal(0, 0.018, len(t_p))    # flat at ~0.24 nm

center_totaltime = 1_000_000   # ps
r1_totaltime     = int(t_r[-1] * 1000)  # ps

ACTIVATION_SASA = 32.10
BC_LOOP_RESIDS  = list(range(30, 36))
CD_LOOP_RESIDS  = list(range(57, 61))

# ── Style ─────────────────────────────────────────────────────────────────────
sys.path.insert(0, str(ROOT / "scripts"))
from plot_style import apply_style, double_width, savefig_pdf as savefig
apply_style()

fig = plt.figure(figsize=(double_width, 4.6))
gs  = fig.add_gridspec(2, 2, hspace=0.60, wspace=0.35,
                       left=0.09, right=0.97, top=0.97, bottom=0.14)

# (a) SASA bursts ─────────────────────────────────────────────────────────────
ax = fig.add_subplot(gs[0, 0])
ax.fill_between(t_r, 22, sasa_r, alpha=0.25, color="#E74C3C")
ax.plot(t_r, sasa_r, color="#E74C3C", lw=1.0)
ax.axhline(ACTIVATION_SASA, color="0.3", lw=1, ls="--", alpha=0.7)
ax.text(0.98, ACTIVATION_SASA + 0.15, f"p95 = {ACTIVATION_SASA:.1f} nm²",
        transform=ax.get_yaxis_transform(), fontsize=7, color="0.35",
        va="bottom", ha="right")
ax.set_xlabel("Time (ns)")
ax.set_ylabel("Hydrophobic SASA (nm²)")
ax.text(0.02, 0.97, "(a)", transform=ax.transAxes,
        fontsize=9, fontweight="bold", va="top", ha="left")
ax.set_ylim(bottom=21.5)

# (b) Rg flat ─────────────────────────────────────────────────────────────────
ax = fig.add_subplot(gs[0, 1])
ax.plot(t_r, rg_r, color="#1ABC9C", lw=1.0, alpha=0.7,
        label="R$_\\mathrm{g}$")
window = max(11, len(rg_r) // 20 | 1)
if len(rg_r) > window:
    sm = sliding_window_view(rg_r, window).mean(axis=1)
    ax.plot(t_r[window//2:window//2+len(sm)], sm,
            color="#16A085", lw=2, label="Rolling avg.")
ax.axhline(rg_r.mean(), color="#444", lw=1, ls="--", alpha=0.7)
ax.set_xlabel("Time (ns)")
ax.set_ylabel("R$_\\mathrm{g}$ (nm)")
ax.text(0.02, 0.97, "(b)", transform=ax.transAxes,
        fontsize=9, fontweight="bold", va="top", ha="left")
ax.text(1.01, rg_r.mean(), f"mean {rg_r.mean():.3f} nm",
        transform=ax.get_yaxis_transform(), fontsize=7, color="#444",
        va="center", ha="left", clip_on=False)
y_pad = 0.04
ax.set_ylim(rg_r.mean() - y_pad, rg_r.mean() + y_pad)
ax.legend(loc="upper right", fontsize=7, framealpha=0.92,
          edgecolor="0.75", handlelength=1.5)

# (c) RMSF CENTER vs R1 ───────────────────────────────────────────────────────
ax = fig.add_subplot(gs[1, 0])
ax.plot(resids_c, rmsf_c, color="#2E86AB", lw=1.2, alpha=0.85,
        label=f"CENTER (bulk, {center_totaltime//1000:.0f} ns)")
ax.plot(resids_r, rmsf_r, color="#E74C3C", lw=1.2, alpha=0.85,
        label=f"R1 (near interface, {r1_totaltime//1000:.0f} ns)")
ax.axvspan(BC_LOOP_RESIDS[0], BC_LOOP_RESIDS[-1], color="#2E86AB", alpha=0.13,
           label=f"Loop BC ({BC_LOOP_RESIDS[0]}–{BC_LOOP_RESIDS[-1]})")
ax.axvspan(CD_LOOP_RESIDS[0], CD_LOOP_RESIDS[-1], color="#E74C3C", alpha=0.13,
           label=f"Loop CD/EF ({CD_LOOP_RESIDS[0]}–{CD_LOOP_RESIDS[-1]})")
ax.set_xlabel("Residue")
ax.set_ylabel("Cα RMSF (nm)")
ax.text(0.02, 0.97, "(c)", transform=ax.transAxes,
        fontsize=9, fontweight="bold", va="top", ha="left")
# FIXED: legend inside axes (lower right — high-residue, low-RMSF region is sparse)
ax.legend(loc="lower right", ncol=1,
          fontsize=7, framealpha=0.92, edgecolor="0.75", handlelength=1.5)
ax.set_xlim(0, max(resids_c.max(), resids_r.max()))

# (d) Patch RMSD ──────────────────────────────────────────────────────────────
ax = fig.add_subplot(gs[1, 1])
ax.plot(t_p, rmsd_p, color="#8E44AD", lw=1.0, alpha=0.6)
sm, sm_times = None, None
if len(rmsd_p) > 11:
    window = max(11, len(rmsd_p) // 20 | 1)
    sm = sliding_window_view(rmsd_p, window).mean(axis=1)
    sm_times = t_p[window//2:window//2+len(sm)]
    ax.plot(sm_times, sm, color="#5B2C6F", lw=2, label="Running mean")

for t_target in [500, 650]:
    if t_target <= t_p[-1] and sm is not None:
        idx_sm = int(np.argmin(np.abs(sm_times - t_target)))
        local  = sm[idx_sm]
        ax.plot(sm_times[idx_sm], local, "o", color="#5B2C6F", ms=6, zorder=5)
        x_offset = -65 if t_target == 650 else 20
        y_offset = +0.045 if t_target == 500 else -0.055
        ax.annotate(f"{local:.3f} nm\n@ {t_target} ns",
                    xy=(sm_times[idx_sm], local),
                    xytext=(sm_times[idx_sm] + x_offset, local + y_offset),
                    fontsize=7.5, color="#4A235A",
                    arrowprops=dict(arrowstyle="-", lw=0.7, color="#8E44AD"))

ax.set_ylim(0.10, 0.32)
ax.set_xlabel("Time (ns)")
# FIXED: shortened ylabel (original "Calyx patch Cα RMSD (nm)" clipped at panel height)
ax.set_ylabel("Patch Cα RMSD (nm)")
ax.text(0.02, 0.97, "(d)", transform=ax.transAxes,
        fontsize=9, fontweight="bold", va="top", ha="left")
# FIXED: legend inside axes (upper left — early-time region)
ax.legend(loc="upper left", fontsize=7, framealpha=0.92, edgecolor="0.75")

savefig(fig, OUT)
print(f"\nLayout preview → {OUT}")
print("NOTE: panels (b) Rg and (d) RMSD use synthetic data.")
print("      Real figure requires: python3 scripts/make_fig3_activation.py")
